{
 "title": "hubitat2prom",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style=\"text-align:center\">House Overview</h1>"
   }
  },
  {
   "title": "House Temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "temperature{job=\"hubitat\"} > -5  ",
     "legendFormat": "{{device_name}}"
    }
   ]
  },
  {
   "title": "Sensor Battery Levels",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "battery{job=\"hubitat\"}",
     "legendFormat": "{{device_name}}"
    }
   ]
  },
  {
   "title": "Detected Light Levels",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "illuminance{job=\"hubitat\"}",
     "legendFormat": "{{device_name}}"
    }
   ]
  },
  {
   "title": "House Humidity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "humidity{job=\"hubitat\"} > -5  ",
     "legendFormat": "{{device_name}}"
    }
   ]
  },
  {
   "title": "Dimmers",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "level{instance=\"hubitat2prom.service.wallace.network:80\",device_name !~ \".+sonos\"}",
     "legendFormat": "{{device_name}}"
    }
   ]
  }
 ]
}